### ISSUE TITLE
contract data

### ISSUE THREAD

**Issue by weallwegot** [roclark/sportsreference#1]
hey, this is an awesome project, love the idea. was literally about to start scraping before i looked around for something. 

any plans to include contract/salary 💰data?

**Comment by roclark** [comment]
Thanks for the kind words, glad you are interested in the project!

I am currently undergoing some final changes for an imminent (at least, I hope!) 0.1.0 release (the first official release of the project) which will contain mostly team-based statistics and information, such as boxscore data, schedules, overall team statistics, etc. Once I release 0.1.0, however, I plan on jumping immediately to development of my next version where I will include roster/player information and, where applicable, information on player salaries! From what I've found so far, the website I am scraping from doesn't necessarily have the best contract/salary information, but I can do some more digging. Any particular sport you are interested in getting this info for? If so, perhaps that will motivate me to work on that sport first. :smile:

**Comment by weallwegot** [comment]
oh awesome sounds good! 

yea its kind of buried away on basketball reference but i see [player stats](https://www.basketball-reference.com/contracts/players.html)  & [team stats](https://www.basketball-reference.com/contracts/GSW.html).  for sure though, don't want to interrupt your release plan, ill definitely be watching the repository & getting a feel for the code in case its a quick PR

**Comment by roclark** [comment]
That's really cool! I haven't spent much time looking at the player information pages yet, so this is new to me, but I will be sure to work on that once I begin my next release! Thanks again for sharing this! I will keep this issue open until I create the new feature so we make sure it's included properly.

**Comment by roclark** [comment]
Closing this for now with the inclusion of the NBA Roster class in #2. If needed, this can be re-opened or commented on if the content should be altered.

**Comment by romainmartinez** [comment]
Hi @roclark, great work! Do you plan to add contract information for NHL players?

**Comment by roclark** [comment]
Hey @romainmartinez! I think this would be a good idea for the future. I haven't added the salaries in yet as they aren't listed on the player's individual page (at least, not that I've found), so this would be a separate feature that would be added. I can certainly add this to a future release. Are you thinking of a specific page? Perhaps the [all NHL current salaries](https://www.hockey-reference.com/friv/current_nhl_salaries.cgi) or [individual team salaries](https://www.hockey-reference.com/teams/DET/2019_salary-cap.html)? Or is there a different page that you desire?
