### ISSUE TITLE
Enhanced teams interface

### ISSUE THREAD

**Issue by baogorek** [roclark/sportsreference#101]
**Is your feature request related to a problem? Please describe.**
The Teams interface can be a bit a clunky when you're learning to use the module. For instance, running:

```
from sportsreference.mlb.teams import Teams
teams = Teams(2017)
print(teams)
```
bombs at the printing statement:
TypeError: __str__ returned non-string (type list)

On the other hand, if running the following code:
```
my_team = teams("HOU")
print(my_team)
```
then I can see that I have a Team object. However, if I go after the schedule with:
```
my_team.schedule
```
then I get another type error.  I can get what I want by specifying that I want the dataframe attribute, but this is not intuitive:

```
hou_schedule = my_team.schedule
df1 = hou_schedule.dataframe
print(df1)
```

**Describe the solution you'd like**
After:

```
teams = Teams(2017)
```
I think onr should be able to
*  print this out and see what type of object it is
* have access to a .show_all() function that lists all of the abreviations
* have positional access to teams, so that teams[1] might be Houston, or some other mechanism that makes it easy to get an arbitrary team.

**Describe alternatives you've considered**
The first section describes a workaround. The package is working great. The interfaces could use some work.

**Comment by roclark** [comment]
Hey @baogorek, I realize this is grossly overdue - I missed this in the issues list as I was working on things over the past year. Thanks for creating this issue, and for the great ideas! A lot of the suggestions you requested here are now part of the standard `sportsreference` package, and it should be easier to determine what each object represents, and to access specific teams. I am going to close this as this is now complete, but thanks again for the great suggestions, and apologies for not getting to this sooner.
