### ISSUE TITLE
Team Roster Errors for Certain NCAAB Teams in Recent Seasons

### ISSUE THREAD

**Issue by alokpattani** [roclark/sportsreference#115]
**Describe the bug**
For certain teams in the 2017-18 NCAAB season (and a couple previous seasons), the Roster object won't load (see example teams below). I think it has to do with broken links to player pages for players who appear on the given team's roster.

**To Reproduce**
from sportsreference.ncaab.roster import Roster, Player
roster = Roster(team = 'houston', year = 2018, slim = False)
roster = Roster(team = 'virginia-tech', year = 2018, slim = False)

**Expected behavior**
Rosters to be returned like they are for the vast majority of NCAAB teams in most seasons.

**Screenshots**
![image](https://user-images.githubusercontent.com/51244947/58829369-84eeb500-85fc-11e9-8df0-7ec4ebc13201.png)

**Desktop (please complete the following information):**
 - OS: Linux (but running in Google Colab in browser, so this shouldn't matter)
 - Sportsreference Version 0.4.3

**Additional context**
As mentioned above, this appears to be an issue with teams having players whose player pages have broken links. I looked at the 2 teams mentioned above and found these "broken" links to player pages (at least they appear broken to me):
- for 2017-18 Houston, Fabian White Jr.: https://www.sports-reference.com/cbb/players/fabian-whitejr-1.html
- for 2017-18 Virginia Tech, Wabissa Bede: https://www.sports-reference.com/cbb/players/wabissa-bede-1.html

Appreciate if these can be fixed for these teams and others!

**Comment by roclark** [comment]
Hello again @alokpattani! Looks like the pages you linked to are fixed at this point, so this technically is resolved, but I still want to make a patch for this to ensure we don't get hit by this again in the future. Looks like the `lxml.etree.ParserError` is thrown during a call to `PyQuery`, so if we catch that error in the `Player` class, similar errors should be avoided. I have another patch incoming which will be merged shortly.

Once again, thank you so much for opening these issues, it greatly helps the project!

**Comment by alokpattani** [comment]
Thanks for "fixing" and putting in the piece to catch the error going forward. I think it was something random that day where those particular pages weren't working on the sports-reference site either, but then they were okay the next day or so. But it sounds like this error catching will help handle better when something like that comes up in the future. Thanks again!
