### ISSUE TITLE
CFB Schedule Load Fails for all seasons before 2013

### ISSUE THREAD

**Issue by cbartok** [roclark/sportsreference#138]
**Describe the bug**
Schedule fails to load due to date not being in the correct datetime format

**To Reproduce**
Sample code which causes an issue.
```python
from sportsreference.ncaaf.schedule import Schedule, Game
Schedule('MARYLAND', 2007).dataframe
```

**Expected behavior**
Schedule loads for the given team and year

**Screenshots**
![image](https://user-images.githubusercontent.com/8619111/61605361-f361f380-abf9-11e9-83c5-962b8df4a0da.png)

**Additional context**
https://www.sports-reference.com/cfb/schools/maryland/2007-schedule.html

The issue is caused because the "Time" column does not exist prior to the 2013 season. 
Hot fix can be implemented by including "or self._time is None" at line 193 in schedule.py but  there may be more elegant ways of doing it.

**Comment by roclark** [comment]
Hello again @cbartok! Another great and detailed report! Nice sleuthing on your part - made it nice and easy to track down. I have a fix ready and will create a PR shortly to get the fix merged with master. I think the additional check for `or not self._time` as you mention is best for here. The logic is already there to check when `self._time` is an empty string, so adding another check is quick and easy. Creating or modifying a property decorator for this or another method would probably be overkill, so I think your proposed solution is the most elegant.

Thanks again for the help and detailed report! I will create the PR shortly!
