### ISSUE TITLE
Iterator over games in some date window

### ISSUE THREAD

**Issue by morelandjs** [roclark/sportsreference#15]
First, wonderful project! I personally would find it useful if I could pull all boxscores in some date window. Neither Boxscore, nor Boxscores is really equipped to do this elegantly. Looks like I'd have to loop over teams, then team schedules, then query boxscore stats using their boxscore id. It would be great if there was a dedicated function to do this.

Examples:
List of all timestamp sorted boxscores 2009--present
List of all boxscores available
List of all boxscores this year

**Comment by roclark** [comment]
Thanks for the kind words sir! This sounds like a great idea! To make sure I understand correctly, for your examples, _all_ boxscores would be returned for those date ranges, regardless of which teams participated? If so, that sounds quite useful to me and would reduce a couple of layers in the querying as you mentioned, both speeding up processing, and reducing the memory footprint of running code. I think this makes sense as an extension to the `Boxscores` class, but am open to other suggestions. I was planning on expanding that class for one of my next updates, so this would probably be the time to incorporate this feature. I will add this to my roadmap for an upcoming release (I will post a new milestone in the coming days).

Thanks again! I really appreciate the feedback!

**Comment by morelandjs** [comment]
Yes, that sounds good. Ideally boxscores should return a single dataframe, with the games ordered by date in one of the axes of that dataframe.

I'm not sure how the underlying code is constructed, but one option is to have boxscores return everything by default, then it widdles down the query based on the function inputs, e.g. date range, team name, etc.

Not sure what the API limits are on sports reference though. Have you ever used nflgame and/or nfldb? They are unmaintained now, but you might get some good ideas from there.
