### ISSUE TITLE
Issue with ncaaf.roster not returning any players

### ISSUE THREAD

**Issue by refekt** [roclark/sportsreference#156]
**Describe the bug**
I am attempting to use the example for Roster() but no players are being returned from Roster().

**To Reproduce**
I even used the example 
```python
from sportsreference.ncaaf.roster import Roster

boilermakers = Roster('PURDUE')
for player in boilermakers.players:
    # Prints the name of all players who played for the Purdue Boilermakers
    # in the most recent season.
    print(player.name)
```

**Expected behavior**
Expected to be able to query a team and get a list of player's stats

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Sportsreference Version 0.4.3

**Comment by soySmelliot** [comment]
It appears that this is likely due to the fact that the 2019 rosters are not populated yet.

**Comment by soySmelliot** [comment]
![image](https://user-images.githubusercontent.com/17421205/62430977-02ac6b00-b6e9-11e9-92c2-024c168dbbd4.png)
 Example from Nebraska's 2019 roster on sports-reference. https://www.sports-reference.com/cfb/schools/nebraska/2019-roster.html

**Comment by roclark** [comment]
Hey @refekt, sorry for not getting to this sooner (been caught up with other projects). @soySmelliot is correct, `sportsreference` was able to retrieve a perfectly valid page for the upcoming season, but there wasn't any actual data on the page, preventing any information from being parsed and players being retrieved. As a result, you are unable to get any players for the current season at this time. Once the team at www.sports-reference.com adds information to the roster pages, you should be able to query it according to the example. Thanks for the great question!

Also, thanks @soySmelliot for the response as well! It's greatly appreciated! :smiley:
