### ISSUE TITLE
from sportsreference.nfl.teams import Teams returns TypeError: 'NoneType' object is not iterable  

### ISSUE THREAD

**Issue by jeffmaxey** [roclark/sportsreference#164]
**Describe the bug**
from sportsreference.nfl.teams import Teams; teams = Teams() returns TypeError: 'NoneType' object is not iterable; likely due to no data existing yet for 2019 season. Please add error handling for this event. 

teams = Teams() ==> error
teams = Teams('2019') ==> error
teams = Teams('2018') ==> no error
  

**To Reproduce**
Sample code which causes an issue.
```python
from sportsreference.nfl.teams import Teams
teams = Teams()
```

```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Temp\Python\.virtualenvs\taco\lib\site-packages\sportsreference\nfl\teams.py", line 505, in __init__
    self._retrieve_all_teams(year)
  File "C:\Temp\Python\.virtualenvs\taco\lib\site-packages\sportsreference\nfl\teams.py", line 639, in _retrieve_all_teams
    team_data_dict = self._add_stats_data(stats_list, team_data_dict)
  File "C:\Temp\Python\.virtualenvs\taco\lib\site-packages\sportsreference\nfl\teams.py", line 592, in _add_stats_data
    for team_data in teams_list:
TypeError: 'NoneType' object is not iterable
```

**Desktop (please complete the following information):**
 - OS: Windows 10, HP Elitebook, Python 3.7
 - Sportsreference Version: pip install -U -I sportsreference

**Comment by jeffmaxey** [comment]
**The URL exists for 2019 but no data exists on the URL** so the situation is not caught in the below code in teams.py and therefore it does not default to 2018 and before.

Please add handler to check if data returned is NoneType.


```python
    def _retrieve_all_teams(self, year):
        """
        Find and create Team instances for all teams in the given season.
        For a given season, parses the specified NFL stats table and finds all
        requested stats. Each team then has a Team instance created which
        includes all requested stats and a few identifiers, such as the team's
        name and abbreviation. All of the individual Team instances are added
        to a list.
        Note that this method is called directly once Teams is invoked and does
        not need to be called manually.
        Parameters
        ----------
        year : string
            The requested year to pull stats from.
        """
        team_data_dict = {}

        if not year:
            year = utils._find_year_for_season('nfl')
            # If stats for the requested season do not exist yet (as is the
            # case right before a new season begins), attempt to pull the
            # previous year's stats. If it exists, use the previous year
            # instead.
            if not utils._url_exists(SEASON_PAGE_URL % year) and \
               utils._url_exists(SEASON_PAGE_URL % str(int(year) - 1)):
                year = str(int(year) - 1)
```

**Comment by roclark** [comment]
Hey @jeffmaxey! Thanks for notifying me of the issue, and especially thanks for the follow-on debugging. You are absolutely right about the page being valid but empty, throwing the error. I think given this scenario just before the start of a season when the pages are live but empty, it would be wise to print a message that no information is available yet for the requested season and handle the errors gracefully. I think this would be preferable to reverting to the previous year in this scenario as some users might want to just know if no information is ready yet. I will get working on a fix for this.

Thanks again!
