### ISSUE TITLE
ncaaf.boxscore.Boxscore.home_players[0] does not have passing attempt

### ISSUE THREAD

**Issue by refekt** [roclark/sportsreference#165]
**Describe the bug**
There is no "pass_attempts" attribute within home_players[] list. There is "pass_yards_per_attempt" and "passing_yards_per_attempt". However there is a "rush_attempts"

**Screenshots**
https://i.imgur.com/dcTbdR4.png

**Desktop (please complete the following information):**
 - OS: Windows 10 
 - Sportsreference Version 0.4.3

**Comment by roclark** [comment]
Hey @refekt, thanks for the issue! I looked over the code and the docs again and found that you are correct, there is no `pass_attempts` attribute for the NCAAF players. Looking further though, I notice that there _is_ a `attempted_passes` attribute which has the expected number of passes a player attempted during the game. For example...

```python
from sportsreference.ncaaf.boxscore import Boxscore

game_data = Boxscore('2018-01-08-georgia')
home_team = game_data.home_players
for player in home_team:
    print(player.name, player.attempted_passes)
```
prints the number of pass attempts for every player as well as their name. In this specific example, it will print `32` attempted passes for Georgia's Jake Fromm, and `None` for all other players.

With that being said, after looking at the docs again, and especially the other attributes you mentioned, I have to admit that I'm not crazy about my original decision to name it `attempted_passes`. While the name is accurate, you generally hear it referred to as "pass attempts" in game or in reports after the fact. Also, it would align with `rush_attempts`. To resolve this, I think I will add a `DeprecationWarning` to `attempted_passes`, and create a duplicate attribute named `pass_attempts`. In a future release down the line, I will remove `attempted_passes` and move forward with `pass_attempts`. Is that fair?

Thanks again for the issue! All of these reports help to make the package as good as it can be!
