### ISSUE TITLE
NBA 2020 Rosters breaking on player nationality

### ISSUE THREAD

**Issue by jpclarkin** [roclark/sportsreference#167]
**Describe the bug**
Unable to pull in roster data for the upcoming 2020 NBA season. Roster function returns an error ('ao') when parsing player nationality.

**To Reproduce**
atl = Roster('ATL',year=2020)

**Expected behavior**
Expected this function to return a number of data points for players on the current roster.

**Screenshots**
https://imgur.com/q5m5IZE

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Sportsreference Version 0.4.2

**Comment by roclark** [comment]
Hey @jpclarkin! Thanks for the issue! Looks like former Terrapin Bruno Fernando is the first ever NBA player from Angola (at least according to sports-reference.com) which is very exciting! As a side effect, `sportsreference` doesn't include support for Angola yet, hence the error for the unknown nation's code. Luckily, this is an easy enough fix and I will include it shortly to resolve this issue.

Thanks again!

**Comment by jpclarkin** [comment]
Hey @roclark ! I think I found another one -- the 76ers roster breaks in a similar fashion. The error code this time is 'td', which is the country code for Chad and the homeland for Sixers rookie Christ Koumadje.

**Comment by roclark** [comment]
Hey @jpclarkin, apologies for the delay! You are absolutely right - I am testing an update now but also identified another issue with the `Roster` module which I need to resolve. I will get this taken care of though!
