### ISSUE TITLE
Boxscore gives empty list for away_players, home_players

### ISSUE THREAD

**Issue by Renaldas55** [roclark/sportsreference#222]
**Describe the bug**
Boxscore gives empty list for away_players and home_players if you try to parse data from 2017 -2018 year. Works for 2019 games, but if you try get players list from 2018 games, list is empty.

**To Reproduce**
from sportsreference.nba.boxscore import Boxscore

game_data = Boxscore('201811030DEN')
a=game_data.home_players
print(a)

**Expected behavior**
List of players

**Screenshots**
![image](https://user-images.githubusercontent.com/56148524/66213618-6d196180-e6c0-11e9-9ab6-8162a1f0fd44.png)

From 2019, we have list.

![image](https://user-images.githubusercontent.com/56148524/66213826-d13c2580-e6c0-11e9-926e-399a90122fc1.png)

**Comment by roclark** [comment]
Hello @Renaldas55, thanks for reaching out! I just did some digging here and found that sports-reference.com changed the table ID format for on the NBA boxscore pages for some older games (but strangely not all as you pointed out). The ID format went from `box_TEAM-game-basic` to `box-TEAM-game-basic` and the code here only catches the former. Luckily, if I check for both ID formats, this should resolve the issue which is a straightforward fix. I will create a patch shortly and get this working properly!

Thanks again for the issue!

**Comment by Renaldas55** [comment]
Hi, Roclark 

Appreciate for quick fix.  Very good application.
