### ISSUE TITLE
Schedule by Date

### ISSUE THREAD

**Issue by santhoshnarayan** [roclark/sportsreference#234]
Is there a current way to get games for a particular date by sport? Right now, it seems the way to do this would be to get every teams schedule and then check each schedule for games happening on a particular date - is that correct?

**Comment by santhoshnarayan** [comment]
Ah, found the method - example for NCAAF:

`
from sportsreference.ncaaf.boxscore import Boxscores
import datetime
Boxscores(datetime.datetime.today()).games
`

**Comment by craigcurtin** [comment]
hi, is there any way to get 'future' games ... as in games tomorrow?
