### ISSUE TITLE
Add field for tourney_placement, championship_won

### ISSUE THREAD

**Issue by pringithub** [roclark/sportsreference#242]
I'd like to see fields for placement of a team in year-end tournaments, and if the team won a championship.

**Comment by roclark** [comment]
Hey @pringithub, thanks for bringing this up! I have a couple of questions for you:

1. What sport are you referring to? I would assume NCAAB and/or NCAAF?
2. Do you have an idea of how you would ideally like this to be implemented? For example, do you want something like a Boolean operator which specifies whether a team made a tournament? ie:

```python
team.made_tournament = True
```
Also, same goes for having won the championship - I would assume a Boolean is appropriate here?

Thanks again for opening this issue! This sounds like a great enhancement and I will put it on my roadmap!

**Comment by pringithub** [comment]
Sure

So looking at the data here: https://www.pro-football-reference.com/teams/det/ (GO LIONS :_( ), there is a category for Div Finish and Playoffs - it would be nice to get these stats in.

For the NFL, for example
```
NFL_PLAYOFF_DICT = { 'LOST_WC': 0, 'LOST_DIV': 1, 'LOST_CONF': 2, 'LOST CHAMP': 3, 'WON CHAMP' : 4 }
class Team ...
...
team.div_finish = int(get_div_finish_from_website()[0]) # first char is finish
team.tourney_placement_str = get_tourney_place_from_website()
team.tourney_placement_enum = NFL_PLAYOFF_DICT[team.tourney_placement]
team.championship_won = (team.tourney_placement_str=='WON CHAMP') or (team.tourney_placement_enum==4) # or whatev
```

I was looking at using your repo for analyzing metrics vs playoff performance so I would need something like the above 😄 

For other sports, will need different things added ..
https://www.baseball-reference.com/teams/DET/
Here, the column header is 'Finish' instead of 'Div Finish' and 'Playoffs' uses MLB-specific strings 'LOST ALDS', 'LOST WS', etc.

**Comment by roclark** [comment]
Thanks for the extra details @pringithub! This looks great, and is definitely something that I can work on adding for a future release! I appreciate the feedback and I will keep you updated on my progress!
