### ISSUE TITLE
NFL Game.result incorrectly reported

### ISSUE THREAD

**Issue by DavidLiuGit** [roclark/sportsreference#245]
**Describe the bug**
NFL games can end in a tie, or may not have a result (e.g. yet to be played, or canceled). However, currently, `Game.result` will return only either loss or win. Games yet to be played are labeled as a win, which is undesired behavior.

**To Reproduce**
```python
# 'Win' is returned for both teams, but this game ended in a tie
2018_pit_cle_wk1_game.result

# this game has yet to be played, but 'Win' is returned for both teams
2019_some_game_wk17.result
```

**Expected behavior**
Correctly return win/loss/tie/unknown for a given `Game`

**Comment by roclark** [comment]
Hey @DavidLiuGit, thanks for putting this together and for #246! I obviously missed this, but it's crucial to have this in as you already know as it unnaturally skews data. I will give you a review on the PR and will merge it once complete so we can get this in. Thanks again!

**Comment by roclark** [comment]
Closing this now that #246 is merged.
