### ISSUE TITLE
NFL season page URL changed

### ISSUE THREAD

**Issue by DavidLiuGit** [roclark/sportsreference#251]
**Describe the bug**
`SEASON_PAGE_URL` should be updated

**To Reproduce**
```python
from sportsreference.nfl.teams import Teams
teams = Teams(2018)
```

**Change required:**
```python
SEASON_PAGE_URL = 'http://www.pro-football-reference.com/years/%s/'
# SEASON_PAGE_URL = 'http://www.pro-football-reference.com/years/%s.html'
``` 

#250

**Comment by roclark** [comment]
Thanks for this issue as well @DavidLiuGit! I will review #250 and let you know what I think! Should be pretty straightforward, and I want to get this in quickly.

**Comment by roclark** [comment]
Closing this with the acceptance of #250. Thanks again for bringing this up and for the fix!
