### ISSUE TITLE
Per 100 Posessions

### ISSUE THREAD

**Issue by LRNBA** [roclark/sportsreference#257]
**Is your feature request related to a problem? Please describe.**
I've just started working with your package and it's been great but I haven't been able to access the per 100 possessions stats for basketball-reference and sports-reference. 

**Describe the solution you'd like**
Would you be able to add this to the Roster module? I think per possession stats are extremely important for leveling the playing field between different teams with different playstyles.

**Comment by roclark** [comment]
Hey @LRNBA, great suggestion! I think this would be good to have, and I agree, these stats provide a unique look at team performances. I will add this to my roadmap and work on including it with a future update.

Thanks again for the suggestion!
