### ISSUE TITLE
Issue w/ team roster response time

### ISSUE THREAD

**Issue by darcyturk** [roclark/sportsreference#26]
**Describe the bug**
Slow response avg. 25-30 seconds to retrieve list of player_ids' in team roster.

**To Reproduce**
`from sportsreference.nba.roster import Roster`
`def get_roster(req, res):`
    `param1 = req.query_params['team']`
    `team = Roster(param1)`
    `players = team.players`
    `res.media = [player.player_id for player in players]`
    `pass`

**Screenshots**
![image](https://user-images.githubusercontent.com/16271621/50254549-4a24f780-03a3-11e9-943a-60384d78d74a.png)

**Desktop (please complete the following information):**
 - OS: macOS Mojave 10.14
 - Sportsreference Version: 0.3.1

**Comment by roclark** [comment]
Hey @darcyturk! So from what I understand, you are looking to just ge the player IDs for each player in a team’s roster? If so, I can add a property just for player IDs, which would make things much quicker, and makes more sense if that’s all that people desire, and individual queries to the `Player` class can be made as needed using those IDs.

As for the performance, the `Roster` class pulls and parses every single player’s individual stats page, which can take 2-3 seconds each. Spread this across 15-20 players, that can take a noticeable amount of time. This is why you are seeing the slow times for this call in your sample code.

With that being said, I can create a new “slim” property which has a dictionary of the players name and ID, which would bypass the call to the individual stats page and speed up performance. Does that sound fair? Regardless, this should be improved, so I will work on it.

Thanks for sharing this!

**Comment by roclark** [comment]
Closed as an update has been merged with master.
