### ISSUE TITLE
Attendance records for CFB

### ISSUE THREAD

**Issue by kbrahm** [roclark/sportsreference#27]
**Is your feature request related to a problem? Please describe.**
It's not a problem so much as a missing piece of what I think is relevant data

**Describe the solution you'd like**
That field added to the endpoint

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by roclark** [comment]
Hey @kbrahm! Thanks for the suggestion! I agree, I think this is a relevant piece of information that I should include with the API. One question for you though, do you have any links or examples of where I can find this information on sports-reference.com? Is this information already provided, or is this something that I would need to calculate?

**Comment by kbrahm** [comment]
I just went back to look but it must have been cfbstats. I probably have made the feedback request to SR.

**Comment by roclark** [comment]
Thanks again @kbrahm! Should I go ahead and close this issue then since it sounds like I won't be able to include it here?

**Comment by kbrahm** [comment]
Yeah - bummer. Sorry.

**Comment by roclark** [comment]
No worries! Glad we could get this somewhat sorted out.
