### ISSUE TITLE
Team Rebounds & Turnovers not Included in CBB Data

### ISSUE THREAD

**Issue by john3842** [roclark/sportsreference#279]
**Describe the bug**
Team Rebounds aren't included in College Basketball Boxscores, so Offensive and Defensive Rebounds are off. For example, if the ball is deflected out of bounds on a rebound, the team that gets the ball OOB gets a team rebound. Same goes for Team Turnovers, potentially Team Technical Fouls (Tech on the coach).

**To Reproduce**
See Box Score for Green Bay vs. Wisconsin on November 21st, 2019. Green Bay should have 25 rebounds, Wisconsin 39.

**Comment by roclark** [comment]
Hey @john3842, thanks for writing this up! I see what you mean about the data missing the team turnovers and rebounds. After looking at the website, however, I am struggling to find anything that indicates team turnovers/rebounds on the boxscore page. For example, I looked at the [game you mentioned](https://www.sports-reference.com/cbb/boxscores/2019-11-21-21-wisconsin.html
), but I only see offensive/defensive rebounds, and total rebounds being the sum of those two. I'm probably looking in the wrong places, but would you mind sharing any details on where I can pull this information from so I can include it?

Thanks again!

**Comment by john3842** [comment]
Hey Robert,

I see what you mean on Sports Reference itself. It looks like there's no "Team Stats" table to easily pull the information from. I was just comparing with ESPN<https://www.espn.com/mens-college-basketball/matchup?gameId=401166085> and CBS<https://www.cbssports.com/college-basketball/gametracker/live/NCAAB_20191121_WISGB@WISC/>' box score for that Wisconsin vs. Green Bay game and noticed the discrepancy.

Unfortunately, I'm not sure if there's an easy way to pull this information. It may not be something worth fixing, as it's not all that common, but I wanted to point it out to you nonetheless just in case. I very much appreciate your work on this API!


Best,


Ryan Johnson

________________________________

**Comment by roclark** [comment]
Thanks for the update @john3842! Yeah, looks like the website is missing that information unfortunately. I think they update their site fairly frequently, so perhaps they will add those stats in the future, but it looks like there isn't a whole lot I can do about this now. Thanks again for bringing this up! I will re-open this if I find that the website gets updated with the info.
