### ISSUE TITLE
Add additional information to documentation - write to csv

### ISSUE THREAD

**Issue by kbrahm** [roclark/sportsreference#28]
**Is your feature request related to a problem? Please describe.**
It's more me being a newbie, but I don't understand yet how to take the data here and be able to write it to a csv

**Describe the solution you'd like**
Additional tutorial in the docs in addition to the great job that has already been completed. 

**Describe alternatives you've considered**
Pasting to notepad

**Additional context**
Appreciate your time, this is an amazing project.

**Comment by jcurrey** [comment]
Pandas makes this super easy!  Take the MLB example:

`from sportsreference.mlb.boxscore import Boxscore `
`game = Boxscore('BOS201806070')`
`df = game.dataframe`

The DataFrame object has a to_csv method:

`from sportsreference.mlb.boxscore import Boxscore `
`game = Boxscore('BOS201806070')`
`df = game.dataframe`
`df.to_csv('path\data.csv')`

**Comment by kbrahm** [comment]
jcurrey - thanks so much!

I used it with this example. 

`from sportsreference.ncaaf.boxscore import Boxscore
import csv

game_data = Boxscore('2018-01-08-georgia')
print(game_data.home_points)  # Prints 23
print(game_data.away_points)  # Prints 26
df = game_data.dataframe  # Returns a Pandas DataFrame of game metrics
print (df)

df.to_csv('box.csv')`

Everything looks good, except the column under stadium is empty, and the column for time has the stadium name and location in the row.

**Comment by kbrahm** [comment]
jcurrey - what would you do for this situation?

`from sportsreference.ncaaf.rankings import Rankings


rankings = Rankings()
# Prints a dictionary of just the team abbreviation and rank for the current
# week.
##print(rankings.current)
# Prints more detailed information including previous rank, full name, and
# movement for all teams for the current week.
##print(rankings.current_extended)
# Prints detailed information for all teams for all weeks where rankings
# have been published for the requested season.
print(rankings.complete)
`
If I do the same thing trying to use pandas I get AttributeError: 'dict' object has no attribute 'dataframe'

**Comment by jcurrey** [comment]
A key thing to remember is data types.  A DataFrame is it's own object with properties and methods.  A dict is a python type, so it looks like you need to create a DataFrame object from that dict object.  And then you can call the df.to_csv method.

Side note–  this is more data wrangling than sports reference.  I'm pretty sure roclark throws us a dataframe object just so we can data wrangle easily.  Pandas is a great with plenty of resources out there, google the pandas library and check some stuff out if you're new to it.  But I imagine this is something you're looking for: 

```python
from sportsreference.ncaaf.rankings import Rankings
import pandas as pd

rankings = Rankings()

list_df = []

rc = rankings.complete

for n in rc:
    df = pd.DataFrame(rc[n])
    list_df.append(df)
    
df_final = pd.concat(list_df)

df_final.to_csv('weekly_rankings.csv')
```

**Comment by roclark** [comment]
Thanks @jcurrey for taking the time to respond here and provide a solid answer!

@kbrahm, does this answer your question, or do you need more help? You have a great idea in enhancing the documentation. I’ve received a few suggestions on adding more in-depth examples and plan on doing that in the future. It would be good to show how to manipulate data, save to a database, and even do things like find the tallest player on a roster, etc. To @jcurrey’s point, I wouldn’t say this is completely within the bounds of `sportsreference`, but it would be great to show others a few ways that you can actually use the package to solve more complex problems.

Lastly, @jcurrey and @kbrahm, do either of you have further questions or suggestions? Are there any features I could/should add here outside of expanding the documentation? If so, I will create a new issue for those features and keep this one open for the documentation update.

Thanks again to both!

**Comment by kbrahm** [comment]
@jcurrey That was exactly what I was looking to see. I know it was more of a general question and I appreciate you taking the time!

@roclark Should I create a bug report on the stadium data being in the time column? How about the error I was receiving when running the source code and figuring out how to use the classes and different years? I'll be sure to let you know if I think of any ways to make improvements or if I see anything that looks off.

**Comment by roclark** [comment]
@kbrahm yeah, opening up a new issue for the stadium data would be good so we can discuss that further and track the progress, as well as any others. I think that would be helpful for people that come to this page in the future to determine a resolution for any issues they run into, so this issue can be kept at documentation. Does that sound fair?

**Comment by kbrahm** [comment]
Sounds good @roclark. Thanks again!
