### ISSUE TITLE
Include coach

### ISSUE THREAD

**Issue by jar211** [roclark/sportsreference#285]
**Is your feature request related to a problem? Please describe.**
Coaches can have a significant influence on the culture of the team and have been shown to have a significant influence on win %. When they change teams the winning follow them.

**Describe the solution you'd like**
I'd like to see the coach included in the data set for the team.

**Describe alternatives you've considered**
I could scrape the page myself.

**Comment by roclark** [comment]
Hey @jar211, great idea! I will work on adding this to the next release, as I agree, coaches are a vital part of the equation and should be included. Thanks for the suggestion! I will close this once the update is merged.

**Comment by mateuszz0000** [comment]
Hello, @roclark are you started working on this issue? I am interesting to contribute and I am wonder which issue I could take for 0.6.0 release :)

**Comment by roclark** [comment]
Hello @mateuszz0000, thanks for reaching out! I have not made any progress on this one yet, so you are free to contribute as desired! I will be very happy to check out a PR when you are ready!
