### ISSUE TITLE
A way to get Advanced rushing and receiving stats?

### ISSUE THREAD

**Issue by BaMarkham1** [roclark/sportsreference#290]
I would like a way to get advanced rushing and advanced receiving stats using this API. That is, Yards After Contact, broken tackles, yards after catch, and yards before catch. I am under the impression this is not available as of now, that is true, correct?

Thanks for any help. I love your API.

**Comment by roclark** [comment]
Hello again @BaMarkham1! You are correct, the advanced rushing and receiving stats are currently not supported by this package, but I would love to add them in a future release. I added them to the 0.6.0 roadmap for the time being and will work on including them for that release. I will keep you updated here as I make progress. Thanks again!
