### ISSUE TITLE
Request to get innings_pitched for a boxscore player as a float instead of an int

### ISSUE THREAD

**Issue by BaMarkham1** [roclark/sportsreference#295]
**Is your feature request related to a problem? Please describe.**

When querying a boxscore player's stats, it returns an integer representing the number of innings a pitcher has pitched in. However, since a pitcher can pitch a fraction of an inning, returning an integer makes the data incomplete. When a pitcher pitches a fraction of an inning, no innings pitched are listed. I need to know exactly how many innings each pitcher pitches in each appearance, and that does not seem to be available.

**Describe the solution you'd like**

List the pitcher's innings in terms of a float, with the fraction, so that the data is accurate. Preferably with (for example) 4.1 meaning the pitcher pitched 4 1/3 innings and 6.2 meaning 6 2/3 innings.

**Describe alternatives you've considered**

Scraping baseball-reference player gamelogs or game pages myself, though I prefer to use the sports-reference package.

**Comment by roclark** [comment]
Hello @BaMarkham1, thanks for taking the time to create this! I apologize for the extremely delayed response, but just wanted to give you a heads up that I created a small patch for this so you should now see partial innings listed in the package for players in the format you gave above. I will create a PR for the patch shortly and include it with my next release which I hope to publish soon.

Thanks again, and sorry for the delay!
