### ISSUE TITLE
player.dataframe fails when weight does not exist

### ISSUE THREAD

**Issue by kevin-steele** [roclark/sportsreference#298]
**Describe the bug**
When sportsreference has no weight for a player (for example: https://www.sports-reference.com/cbb/players/kenny-maccalla-1.html) the player.dataframe call fails. This is because the code assumes the `self._weight` variable will be a string, but it can be `None`.

**To Reproduce**
```
from sportsreference.ncaab.roster import Player
player = Player('kenny-maccalla-1')
print(player.name)
print(player.weight)
print(player.dataframe)
```

**Expected behavior**
In the code above, I expected player.weight to return an empty string, None, or a placeholder value like `0`. Additionally I expected player.dataframe to return a dataframe with the players stats, including an empty string, None, or a placeholder value like `0` for the weight column.

This might not be elegant enough for you but you could simply do something like the following:
```
    @property
    def weight(self):
        """
        Returns an ``int`` of the player's weight in pounds.
        """
        if self._weight is not None:
            return int(self._weight.replace('lb', ''))
        else:
            return 0
```

**Desktop (please complete the following information):**
 - OS: 10.14.6
 - Sportsreference Version 0.4.7

**Additional context**
This seems to only affect the package when calling roster dataframes for older seasons, since recent seasons have weights for all/most players. This might be affecting additional variables, too.

**Comment by roclark** [comment]
Hello @kevin-steele, thanks for the report and the thorough write-up! This makes debugging much easier! 😃 You are spot-on about the issue. I've created a small patch which should resolve the issue and will include it in the next release (which should be in the coming days, hopefully).

I apologize for the delinquent response - I'm currently changing jobs and haven't had much time to dedicate here, but I appreciate the report and will get this fixed ASAP!

**Comment by kevin-steele** [comment]
No worries -- thanks for addressing!
