### ISSUE TITLE
How can I get a player's stats before/after a certain game, or at a certain point in time?

### ISSUE THREAD

**Issue by gabespound** [roclark/sportsreference#345]
I'm trying to use player data to predict the outcome of games, but I don't see a way to get historical player stats, just the most up to date stats for each player.

**Comment by roclark** [comment]
Hey @gabespound, thanks for the question! To make sure I understand correctly, are you wanting to find a particular player’s season or career stats on a particular day, such I as Tom Brady’s stats after week 3 (ie. games 1-3, but no others)? If so, this package doesn’t support that functionality unfortunately as the website is updated daily with the latest information.

One way to potentially get around this, however, is to pull all relevant stats in the morning on a daily basis and run any algorithms or append a dataset with changes. Not a perfect solution, but it could work depending on your needs.

Additionally, you check the player’s stats for every game in a particular range and sum the stats. Perhaps that would work?

Given how the website updates, I won’t be able to add this feature, sadly, unless they make changes to viewing data in more of a time-series format or something along those lines.

Hope this helps!

**Comment by roclark** [comment]
Closing as no new updates. Feel free to re-open or create a new issue if further assistance is required. Thanks!
