### ISSUE TITLE
NCAAF stats not being fetched

### ISSUE THREAD

**Issue by AidanGlickman** [roclark/sportsreference#362]
**Describe the bug**

Several fields are not being fetched for NCAAF players. I checked the ncaaf constants against the sportsreference page and it seems to all be correct, so I am not sure what the issue is.

**To Reproduce**

```python
from sportsreference.ncaaf.roster import Player

odell = Player("odell-beckham-jr-1")
print(odell.receptions)
```

**Expected behavior**

expected `143` as per SportsReference, got `None`

**Screenshots**

**Desktop (please complete the following information):**

 - OS: MacOS Catalina 10.15
 - Sportsreference Version 0.5.0

**Additional context**

[Here](https://www.sports-reference.com/cfb/players/odell-beckham-jr-1.html) is a link to the page used in the example.

**Comment by roclark** [comment]
Thanks @AidanGlickman for the details! I just took a dive into the source for OBJ's stats page and found that the ID for the "Receiving and Rushing" table is `receiving`, which I was not parsing. Apparently, this same table has an ID of `rushing` for most players, but `receiving` for a handful of others. I tested adding `receiving` to the list of table IDs to pull, and it looks like the correct stats are being returned (143 career receptions) now. I will create and merge a patch shortly and will include this with my next patch release.

Thanks again for the report! I greatly appreciate the details!
