### ISSUE TITLE
Key Error

### ISSUE THREAD

**Issue by denutza** [roclark/sportsreference#365]
from sportsreference.ncaab.teams import Teams
from sportsreference.ncaab.schedule import Schedule

teams=Teams(year=2010)

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-17-3099ceb9fc77> in <module>
----> 1 teams=Teams(year=2010)

c:\python36\lib\site-packages\sportsreference\ncaab\teams.py in __init__(self, year)
    997         self._conferences_dict = Conferences(year).team_conference
    998 
--> 999         self._retrieve_all_teams(year)
   1000 
   1001     def __getitem__(self, abbreviation):

c:\python36\lib\site-packages\sportsreference\ncaab\teams.py in _retrieve_all_teams(self, year)
   1140         for team_name, team_data in team_data_dict.items():
   1141             team = Team(team_data['data'],
-> 1142                         self._conferences_dict[team_name.lower()],
   1143                         year)
   1144             self._teams.append(team)

KeyError: 'bryant'

I tried year 2011 and it worked fine.

**Comment by roclark** [comment]
Hello @denutza! Thanks for creating the issue! I just took a look, and there's something weird going on with Bryant University around that year. Apparently, they started their transition to Division-I basketball a couple years before, and fully converted a couple years later (at least, according to their [basketball Wiki page](https://en.wikipedia.org/wiki/Bryant_Bulldogs_men's_basketball)). Looking at sports-reference.com, they are listed in the school stats sections for 2010, but they don't have an individual school page that year, causing them to not be populated in the dictionary containing conference details, and throwing the `KeyError` you ran into.

I was able to make a quick patch to check if the school contains valid information before attempting to create a `Team` instance and it appears to be working correctly now. I will create a new PR with the patch shortly and get this merged in for the next release.

Thanks again!

**Comment by denutza** [comment]
Thank you for the fast response.
I found out its happening on at least another year if not more.

Try this:
from sportsreference.ncaab.teams import Teams
from sportsreference.ncaab.schedule import Schedule

season_range=[]
for i in range(2000,2020,1):
    season_range.append(i)

NCAAF works flawlessly.
for x in season_range:
    teams=Teams(year=x)

**Comment by roclark** [comment]
Thanks for the update! I just ran through that test using the patch and it is able to continue normally, so I think this issue has been resolved for now, but please open another issue if you feel otherwise. I will hopefully get another release out in the near-term so this patch will be included with all released binaries.
