### ISSUE TITLE
Add Time to Schedule Dataframes

### ISSUE THREAD

**Issue by denutza** [roclark/sportsreference#384]
I was wondering if you can add the actual time of the game to your schedule dataframes datetime object.

From what I can see, its just a redundant column to the date column as it doesn't indicate the time the game went off.

And in the case of pro-football reference, the time is certainly available on the page your scraping.

I cross reference my db with the weather, where i need the actual time of the event.

Thanks!

**Comment by roclark** [comment]
Hey @denutza, thanks for the great suggestion! I will add this to my roadmap and get this included with a future release. I appreciate it!

**Comment by denutza** [comment]
Could you add the time for all sports? In particular MLB.
