### ISSUE TITLE
Error: No module named Sportsreference.fb

### ISSUE THREAD

**Issue by Maths-Lad** [roclark/sportsreference#389]
Hi again, I followed the installation guide, but after inputting in python:
'Import Sportsreference.fb' 
it still gives me the same error, so the latter stages of the football data also do not work.

What codes should I use? 
Should I just follow your guide, or is the problem still being fixed/updated?

Many thanks.

**Comment by roclark** [comment]
Hello again @Maths-Lad, you are correct, this is still broken for the latest binary as the updated version hasn't been pushed yet (the original binary you pulled for your previous issue is still the latest version), though this should work if you compile a wheel from source now. I just initiated a publishing task which should complete in a few hours, then you can update to the latest binary and try again where it should work for you. I will update here when I've tried out the new binary and let you know.

Thanks!

**Comment by roclark** [comment]
Looks like the new wheel has been published to PyPI, so you can upgrade with:
```bash
pip install --upgrade sportsreference
```

Now, the following will work:
```python
from sportsreference.fb.team import Team

tottenham = Team('Tottenham Hotspur')
print(tottenham.goals_scored)
```

Let me know if you are still having issues with this and we can try and sort it out.

**Comment by Maths-Lad** [comment]
Yes, it seems to work now! Thank you very much for your help.

**Comment by roclark** [comment]
Great, thanks for the confirmation!
