### ISSUE TITLE
'NoneType' object has no attribute 'replace'

### ISSUE THREAD

**Issue by denutza** [roclark/sportsreference#393]
Bug has something to do with a players weight. Maybe it couldnt find the 'lb' tag for some of the players:

 
> --> 666         return int(self._weight.replace('lb', ''))
>     667 
>     668     @property
> 
> AttributeError: 'NoneType' object has no attribute 'replace'

To reproduce:

> r=Roster('NYG',2013)
> for p in r.players:
>     print(p.dataframe)

**Comment by roclark** [comment]
Thanks for identifying this @denutza! You are right - there is an issue finding weights for some players, hence this error. I will create a patch for this and roll it into the next release. Thanks again!
