### ISSUE TITLE
trying to connect to sportsreference.nba.schedule receiving a requests.exceptions.ConnectionError

### ISSUE THREAD

**Issue by Lzm0010** [roclark/sportsreference#414]
i am able to import mlb and nfl but the when i try to get nba schedule module i get this error:

"requests.exceptions.ConnectionError: HTTPConnectionPool(host='www.basketball-reference.com', port=80): Max retries exceeded with url: /teams/HOU/2020_games.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x124bdc668>: Failed to establish a new connection: [Errno 61] Connection refused'))"

```python
from sportsreference.nba.schedule import Schedule 

df = Schedule("HOU").dataframe
print(df)
```

Is this module down? other sports are working and the imports and call to use are identical. Thanks

**Comment by roclark** [comment]
Hey @Lzm0010, thanks for bringing this to my attention! It's possible this was a temporary issue on their side as it wasn't able to pull the page. This will happen occasionally, or if networking is down briefly. I am not seeing anything on my end currently. Are you still running into this?

**Comment by Lzm0010** [comment]
yes, i am still running into this issue

**Comment by Lzm0010** [comment]
it was my Internet service provider, switched to a hot spot from my phone and the nba modules worked.
Sorry for the false alarm.
