### ISSUE TITLE
NBA quarter points do not work

### ISSUE THREAD

**Issue by fasgaas** [roclark/sportsreference#455]
**Describe the bug**
Just the summary for NBA quarter points do not work. It worked before so i guess they changed something

**To Reproduce**
from sportsreference.nba.boxscore import Boxscore

game_data = Boxscore('201806080CLE')
print(game_data.summary)

**Comment by roclark** [comment]
Hey @fasgaas, thanks for bringing this to my attention! It appears the website was updated and now has an extra space in the class attribute for the game summary table for the NBA boxscores, which made the summary turn up empty. I have a fix for this coming and will merge it shortly. Thanks for the notice!
