### ISSUE TITLE
Teams() giving http error

### ISSUE THREAD

**Issue by arun1125** [roclark/sportsreference#464]
**Describe the bug**

**To Reproduce**
Sample code which causes an issue.
```python
location = "here"
print("Example python code %s" % location)
```

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu 18.04]
 - Sportsreference Version [e.g. 0.2.0 or commit hash if using code]

**Additional context**
Add any other context about the problem here. If applicable, also include links to any pages on www.sports-reference.com that are believed to be causing this issue.

**Comment by arun1125** [comment]
from sportsreference.nba.teams import Teams

teams = Teams() gives an http error

**Comment by scaratozzolo** [comment]
Try this for teams
```python
teams = Teams(year=2020)
```

For the schedules, the abbreviations you're using I don't believe are correct. Try, BRK, CHO, and PHO.

**Comment by arun1125** [comment]
Thank you so much!

**Comment by roclark** [comment]
Hey @arun1125, thanks for filing this issue! Apologies for not getting to this sooner. Sadly, it looks like this is a result of the continued pandemic as the delays in the NBA season have caused the logic used in the default season selector invalid, as the package assumes the 2021 season should be getting ready to begin at this point. @scaratozzolo gave an awesome workaround in the meantime (thanks Scott!!!) which looks like it is working for you, but I am finalizing a patch that handles the logic for this scenario and will push it out shortly.

Thank you both for working together to identify the issue and find a workaround! I will close this issues once everything works as expected and the original functionality is restored, ie:

```python
from sportsreference.nba.teams import Teams

teams = Teams()
```
