### ISSUE TITLE
Datetime object of an NFL Game do not contains "time".

### ISSUE THREAD

**Issue by fx182ch** [roclark/sportsreference#469]
**Describe the bug**
Datetime object of an NFL Game do not contains "time".

**To Reproduce**
Sample code which causes an issue.
```python
>>> schedule_nwe = Schedule("NWE")
>>> print(schedule_nwe[0].datetime)
2020-09-13 00:00:00
```

**Expected behavior**
When requesting for a datetime of a game I expect to have date and time of the game.

**Screenshots**
![image](https://user-images.githubusercontent.com/3285637/93086519-8af49200-f697-11ea-9a2e-b991e9d10c89.png)

![image](https://user-images.githubusercontent.com/3285637/93086552-9778ea80-f697-11ea-8ab7-77ca71932c16.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 / script running on Windows Subsystem for Linux (WSL) / python 3.6.9
 - Sportsreference Version: 0.5.2

**Additional context**
https://www.pro-football-reference.com/teams/nwe/2020.htm

**Comment by vatsal-M** [comment]
Our team @ISD14-LNMIIT wants to work on this issue. Please assign this issue to us!
@fx182ch

**Comment by roclark** [comment]
Hey @fx182ch, thanks for bringing this up! Correct, the time is not included with the NFL schedules. The package actually pulls data from a different location on the website for each team (the [gamelog](https://www.pro-football-reference.com/teams/nwe/2020/gamelog/) for the Patriots for example). While the gamelog has additional high-level information for each team that is useful in the stats, it actually doesn't include the scheduled start time on the page. This is a limitation of the sports-reference.com gamelogs and unfortunately this can't be changed unless the source for the `Schedule` module is changed which would sacrifice the other high-level information that some look for in the schedules. As a result, I don't think an update can be made here given the structure of the site, but if the game times are added to the gamelogs, I would be very happy to make that change to the package. For now, I will close this issue. Thanks again for bringing this up!
