### ISSUE TITLE
NBA Boxscores() returns incorrect home_points

### ISSUE THREAD

**Issue by sseljan** [roclark/sportsreference#470]
**Describe the bug**
When using the Boxscore method from NBA games, I am getting the wrong results for the home_XXXX metrics. 

**To Reproduce**
Sample code which causes an issue.
```
from sportsreference.nba.boxscore import Boxscore
Boxscore('202009130DEN').dataframe[['home_points','away_points',
'home_two_point_field_goals','away_two_point_field_goals']]
```

**Expected behavior**
Method returns the correct full game box score for both home and away teams. 

**Screenshots**
result of code above:
```
              home_points  away_points  home_two_point_field_goals  away_two_point_field_goals
202009130DEN           64           98                          10                          22
```

**Desktop:**
 - OS: MacOS
 - Sportsreference Version 0.5.2

**Additional context**
The boxscore method worked correctly prior to 9/9/2020

**Comment by dropthemic** [comment]
You can fix it by changing in file `nba/constants.py`:
```
'home_points': 'tfoot td[data-stat="pts"]'
to
'home_points': '.score'
```

Output:
```
home_points                   111
away_points                    98
home_two_point_field_goals     10
away_two_point_field_goals     22
```
I didn't unit test this and not sure if this breaks other pages...

**Comment by roclark** [comment]
Hey @sseljan, thanks for bringing this to my attention! Looks like the website changed the layout slightly, so the 64 that you are seeing there is actually the home team's second half point total, which is obviously incorrect. @dropthemic's wonderful solution fixes the problem (thank you for sharing!!), and I have a patch in the works that I hope to merge shortly so this can be updated in the upstream code. Thanks again to you both for the help!

**Comment by sseljan** [comment]
Awesome!

**Comment by sseljan** [comment]
While I really appreciate that you've addressed this, I should note that all of the home stats (field goals, blocks, steals, etc) are from the second half. I could have labeled the issue more clearly. 

As I read the solution above, it wasn't clear to me if it only corrects the points or all stats.
