### ISSUE TITLE
NBA home stats are not scraped correctly

### ISSUE THREAD

**Issue by thomaslu2** [roclark/sportsreference#498]
When modifying the NBA boxscore test file, I came across a bug where the home team stats for a game are not scraped correctly. Basketball Reference changed the website so that it can support quarter-by-quarter stats. What happens now is that the Q1 stats of the away team are now recognized as the stats for the home team. However, the home team advanced stats are scraped correctly. For reference, the game that I used for the test file is [here (Rockets vs Jazz)](https://www.basketball-reference.com/boxscores/202002220UTA.html)

**Comment by roclark** [comment]
Thanks @thomaslu2! I'm looking into this now. Looks like I will need to find a crafty way to get the index of the home team for the full-game stats, but I will see what I can find and create a fix. Thanks!
