### ISSUE TITLE
NCAAF multiple boxscores does not scrape correctly when on certain date

### ISSUE THREAD

**Issue by thomaslu2** [roclark/sportsreference#499]
When modifying the NCAAF Boxscore test file, I came across this bug where it will not scrape correctly when the date you choose have games on those days. For example, there is a slight difference in the page source between [Saturday 9/12](https://www.sports-reference.com/cfb/boxscores/index.cgi?month=9&day=12&year=2020) and [Sunday 9/13](https://www.sports-reference.com/cfb/boxscores/index.cgi?month=9&day=13&year=2020&conf_id=). The 9/13 page has an extra `tr` within the `div` to account for the date while the 9/12 does not have that extra table row. Otherwise, the main functionality works fine.

**Comment by roclark** [comment]
Hey @thomaslu2, thanks for identifying this! Do you mind explaining a bit more about the issue? I see what you mean about the extra `tr` with the date on those boxscores, but is this throwing an issue on your end? I can pull Boxscores for both 9/12 and 9/13 without errors with the latest upstream code. I'd be happy to look into this and fix something if needed. Thanks again!

**Comment by thomaslu2** [comment]
Yeah I should have been more clear with this issue. When I tried using 9/12 as the expected data, it will throw and error and say that the home team is both the away and home team. It will work as expected when 9/13 and 9/14 used as the input instead. The issue here is that it does not get the data correctly if you choose a date that does have games on that day. So it works correctly when there is that extra `tr` as seen in 9/13.

**Comment by romanbogza** [comment]
I am facing the same issue. Can you please clarify what is the fix here? I'm also seeing same team for away and home.

**Comment by roclark** [comment]
Thank you both for the feedback! I just created PR #504 which should resolve this issue. Thankfully, it just needed some simple branching logic to handle. Once that PR passes the tests, I will merge it and mark this as closed. Thanks again!
