### ISSUE TITLE
NCAAF Boxscore data not correct. See below.

### ISSUE THREAD

**Issue by romanbogza** [roclark/sportsreference#503]
See example below. I am querying boxscore for a particular day (10-14-2020) and I am getting for both home and away team as Louisiana-Lafayette. Something is up.

{'boxscore': '2020-10-14-louisiana-lafayette', 'away_name': 'Louisiana', 'away_abbr': 'louisiana-lafayette', 'away_score': None, 'away_rank': 21, 'home_name': 'Louisiana', 'home_abbr': 'louisiana-lafayette', 'home_score': None, 'home_rank': 21, 'non_di': False, 'top_25': True, 'winning_name': None, 'winning_abbr': None, 'losing_name': None, 'losing_abbr': None}

**Comment by roclark** [comment]
Thanks for reaching out! Per the discussion in #499, I will close this as a duplicate. PR #504 should be merged soon to resolve this issue. Thanks!
