### ISSUE TITLE
Football - Premiere League Male Teams / Squad_ids missing

### ISSUE THREAD

**Issue by clemlaplace** [roclark/sportsreference#515]
Some Premiere League male teams are missing when being called by their squad_id. Only the women version of those squads are found.

Code Example for Manchester City - Python:

from sportsreference.fb.team import *
tot=Team('b8fd03ef')

[]
Exact match not found - Printing closest matches:

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-242-a2af02f0576b> in <module>
      1 from sportsreference.fb.team import *
      2 
----> 3 tot=Team('b8fd03ef')

~\Documents\git\sportsreference\sportsreference\fb\team.py in __init__(self, team_id, squad_page)
     66         self._away_points = None
     67 
---> 68         self._squad_id = _lookup_team(team_id)
     69         self._pull_team_page(squad_page)
     70 

~\Documents\git\sportsreference\sportsreference\fb\fb_utils.py in _lookup_team(team_id)
    127     error_message = ('Team ID of "%s" not found. Did you mean one of the '
    128                      'following?\n%s' % (team_id, name))
--> 129     raise ValueError(error_message)

ValueError: Team ID of "b8fd03ef" not found. Did you mean one of the following?
{}

When the code should return all the information about the team, as it does with other premiere league teams.

**Comment by roclark** [comment]
Hey @clemlaplace, thanks for bringing this to my attention! Looks like the ID saved for Manchester City in the package actually points to the women's team, so the ID you provided (which should map to the men's team) doesn't exist. I will create a small patch to fix this so the men's team can be retrieved. Thanks for the update!
