### ISSUE TITLE
VEgas 

### ISSUE THREAD

**Issue by jernej19** [roclark/sportsreference#99]
Hi!
It seems URL for Vegas roster is wrong. I get an error that it's calling https://www.hockey-reference.com/teams/veg/2019.html instead https://www.hockey-reference.com/teams/VEG/2019.html

**Comment by roclark** [comment]
Hello @jernej19! Thanks for posting! I will track down why the team's abbreviation isn't being set to uppercase. Should be a straightforward fix on my part.
